services:
  data:
    build: ./data
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    environment:
      - MONGO_INITDB_DATABASE=CSE356

  gateway:
    build: ./gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Mount the certs directory to access the SSL certificates
      - ./nginx.conf:/root/milestone3/gateway/nginx.conf  # Correct the path for nginx.conf
    environment:
      - VIRTUAL_HOST=bubbleguppies.cse356.compas.cs.stonybrook.edu
    depends_on:
      - data  # Gateway depends on the data service

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Shared volume for Certbot certificates
      - ./nginx.conf:/root/milestone3/gateway/nginx.conf  # Correct the path for nginx.conf (use /etc/nginx/nginx.conf)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certbot certonly --webroot --webroot-path=/var/www/certbot --email billy.li.1@stonybrook.edu --agree-tos --no-eff-email --staging
    depends_on:
      - gateway  # Certbot must wait for gateway to be ready

  # mailserver:
  #   build: ./mailserver
  #   ports:
  #     - "25:25"
  #     - "587:587"
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4

  # media:
  #   build: ./media

  # haproxy:
  #   image: haproxy:latest
  #   container_name: haproxy
  #   ports:
  #     - "5200:8080" # Expose HAProxy on port 8080
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro # Mount HAProxy config file
  #   depends_on:
  #     - app1
  #     - app2
  #     - app3
  #     - app4
  #     - app5
  #     - app6
  #     - app7
  #     - app8
  #     - app9
  #     - app10

  # app1:
  #   build: ./app
  #   ports:
  #     - "7000:5200"

  # app2:
  #   build: ./app
  #   ports:
  #     - "7100:5200"

  # app3:
  #   build: ./app
  #   ports:
  #     - "7200:5200"

  # app4:
  #   build: ./app
  #   ports:
  #     - "7300:5200"

  # app5:
  #   build: ./app
  #   ports:
  #     - "7400:5200"
  
  # app6:
  #   build: ./app
  #   ports:
  #     - "7500:5200"

  # app7:
  #   build: ./app
  #   ports:
  #     - "7600:5200"

  # app8:
  #   build: ./app
  #   ports:
  #     - "7700:5200"

  # app9:
  #   build: ./app
  #   ports:
  #     - "7800:5200"

  # app10:
  #   build: ./app
  #   ports:
  #     - "7900:5200"
  #   build: ./app
  #   ports:
  #     - "7400:5200"
